defaults:
  - hydra: default
  - model: dyn_unet_base
  - _self_

# i/o
image_path: './input_vesselFM' #TODO
image_file_ending: nii.gz
output_folder: './output_vesselFM' # TODO
file_app: ""

mask_path: null
round_to: 2

# model & ckpt
device: cuda:0
ckpt_path: /path/to/ckpt.pt

# sliding window inferer
batch_size: 4  #TODO Adjust this batch size based on your device.
patch_size: [128, 128, 128]
overlap: 0.5
mode: "constant"
sigma_scale: 0.125
padding_mode: "constant"

# eval & reproducibility
seed: 404

## standard pre-processing transforms #TODO I used Hu window, you can use the percentile of intensity
#transforms_config:
#  - EnsureChannelFirst:
#      channel_dim: "no_channel"
#  - ScaleIntensityRangePercentiles:
#      lower: 1
#      upper: 99
#      b_min: 0
#      b_max: 1
#      clip: true
#  - ToTensor:
#      device: null

# standard pre-processing transforms
transforms_config:
  - EnsureChannelFirst:
      channel_dim: "no_channel"
  - ScaleIntensityRange:
      a_min: -500  # The lower end of your HU window #TODO Adjust this based on your application
      a_max: 500   # The upper end of your HU window #TODO Adjust this based on your application
      b_min: 0     # The lower end of the output range
      b_max: 1     # The upper end of the output range
      clip: true
  - ToTensor:
      device: null

# test time augmentation
tta:
  scales: [1] #[0.5, 1, 1.5]
  invert: false
  invert_mean_thresh: 0.5
  equalize_hist: false
  hist_bins: 100

# post-processing
post:
  apply: False
  small_objects_min_size: 50   #TODO Adjust this based on your application
  small_objects_connectivity: 3

# merging
merging:
  threshold: 0.5    #TODO Adjust this based on your application.
  max: false